const ratingTypes = {
  GET_POST_RATING_START: "GET_POST_RATING_START",
  SET_RATING: "SET_RATING",
  RESET_RATING_STATE: "RESET_RATING_STATE",
  HANDLE_STAR_START: "HANDLE_STAR_START",
};

export default ratingTypes;
