const productsTypes = {
  ADD_NEW_PRODUCT_START: "ADD_NEW_PRODUCT_START",
  FETCH_PRODUCTS_START: "FETCH_PRODUCTS_START",
  SET_PRODUCTS: "SET_PRODUCTS",
  DELETE_PRODUCT_START: "DELETE_PRODUCT_START",
  ///////////
  FETCH_PRODUCT_START: "FETCH_PRODUCT_START",
  SET_PRODUCT: "SET_PRODUCT",
  /////////////
  IS_LOADING: "IS_LOADING",
  ///////////////
  GET_PRODUCT_RATING_START: "GET_PRODUCT_RATING_STAR",
  SET_PRODUCT_RATING: "SET_PRODUCT_RATING",
  //////////////////////
  HANDLE_RATE_START: "HANDLE_RATE_START",
  HANDLE_SELECTED_PRODUCT_RATE_START: "HANDLE_SELECTED_PRODUCT_RATE_START",
  SET_SELECTED_PRODUCT_RATING: "SET_SELECTED_PRODUCT_RATING",
};

export default productsTypes;
